# syntax=docker/dockerfile:1.7

# ---------- Stage 1: install deps ----------
FROM node:24-slim AS deps
WORKDIR /app

# Enable pnpm via corepack (matches the pinned version in package.json's packageManager
# field if set; falls back to corepack's bundled pnpm otherwise).
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Mounted cache means rebuilding only re-downloads deltas, not the full registry.
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm config set store-dir /pnpm/store && \
    pnpm install --frozen-lockfile

# ---------- Stage 2: build ----------
FROM node:24-slim AS builder
WORKDIR /app
RUN corepack enable

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js telemetry off in CI/build. Output mode 'standalone' is set in next.config.ts.
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm build

# ---------- Stage 3: runtime ----------
FROM node:24-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user for the runtime.
RUN groupadd --system --gid 1001 nodejs && \
    useradd --system --uid 1001 --gid nodejs nextjs

# Public assets (preset reference images, etc.) ship inside the image.
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# The standalone build is a self-contained server with only the required deps.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Runtime state directory (json db + per-image prompt cache).
# Mount this as a volume in production to persist between restarts:
#   docker run -v sceneify_data:/app/data ...
RUN mkdir -p /app/data /app/public/uploads && \
    chown -R nextjs:nodejs /app/data /app/public/uploads

USER nextjs

EXPOSE 3000

# server.js is generated by next build with output: 'standalone'.
CMD ["node", "server.js"]
